Repository napzakmarket/Napzak-BE, pull requests merged in 2025-07, with the labels that each got.

#103 [deploy] #102 - dev-CD 수정
  .github/workflows/dev-CD.yml
Labels: deploy 🚀, 혜린😼

#104 [deploy] #102 - dev-CD 수정
  .github/workflows/dev-CD.yml
Labels: deploy 🚀, 혜린😼

#106 [deploy] #105 - deploy 수정
  Dockerfile-api-dev
  Dockerfile-chat-dev
  docker-compose-dev.yml
Labels: deploy 🚀, 혜린😼

#107 [deploy] #105 - jar 파일 이름 변경
  Dockerfile-api-dev
  Dockerfile-chat-dev
  api-server/build.gradle
  build.gradle
  chat-server/build.gradle
  common-module/build.gradle
  core-domain/build.gradle
  docker-compose-dev.yml
Labels: deploy 🚀, 혜린😼

#109 [fix] #108 - FirebaseConfig 수정
  common-module/src/main/java/com/napzak/common/config/FirebaseConfig.java
Labels: fix 🛠️, 혜린😼

#111 [fix] #110 - Dockerfile 수정
  Dockerfile-api-dev
  Dockerfile-chat-dev
Labels: fix 🛠️, 혜린😼

#121 [fix] #120 - Interest, Token parameter name binding issue 해결
  api-server/build.gradle
  common-module/src/main/java/com/napzak/common/auth/jwt/repository/TokenRepository.java
  common-module/src/main/java/com/napzak/common/auth/redis/Token.java
  core-domain/src/main/java/com/napzak/domain/product/repository/ProductRepository.java
Labels: fix 🛠️, 혜린😼

#126 [chore] #124 - MessageMapping 경로 변경
  chat-server/build.gradle
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/controller/ChatWebSocketController.java
  chat-server/src/main/resources/static/ws-test.html
Labels: chore 🔍, 혜린😼

#129 [fix] #128 - 상품 개수 불일치 문제 해결
  api-server/src/main/java/com/napzak/api/domain/product/ProductStoreFacade.java
  api-server/src/main/java/com/napzak/api/domain/product/controller/ProductController.java
  api-server/src/main/java/com/napzak/api/domain/product/service/ProductService.java
  core-domain/src/main/java/com/napzak/domain/store/crud/store/StoreRetriever.java
  core-domain/src/main/java/com/napzak/domain/store/repository/StoreRepository.java
  core-domain/src/main/java/com/napzak/domain/store/vo/StoreStatus.java
Labels: bug 🐞, fix 🛠️, 세희🐰

#130 [feat] #127 - 푸쉬 테스트 REST api 구현
  chat-server/src/main/java/com/napzak/chat/domain/push/api/code/PushSuccessCode.java
  chat-server/src/main/java/com/napzak/chat/domain/push/api/controller/PushTokenController.java
  chat-server/src/main/java/com/napzak/chat/domain/push/api/dto/request/PushTestRequest.java
  core-domain/src/main/java/com/napzak/domain/push/code/PushErrorCode.java
  core-domain/src/main/java/com/napzak/domain/push/util/FcmPushSender.java
Labels: feat 🎯, 세희🐰

#117 [feat] #116 - api 별 허용 store role 어노테이션 부여
  api-server/src/main/java/com/napzak/api/domain/banner/controller/BannerController.java
  api-server/src/main/java/com/napzak/api/domain/file/controller/FileController.java
  api-server/src/main/java/com/napzak/api/domain/genre/controller/GenreController.java
  api-server/src/main/java/com/napzak/api/domain/interest/controller/InterestController.java
  api-server/src/main/java/com/napzak/api/domain/product/controller/ProductController.java
  api-server/src/main/java/com/napzak/api/domain/store/controller/StoreController.java
  api-server/src/main/java/com/napzak/api/domain/store/service/AuthenticationService.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/controller/ChatRestController.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/controller/ChatWebSocketController.java
  chat-server/src/main/java/com/napzak/chat/domain/push/api/controller/PushTokenController.java
  core-domain/src/main/java/com/napzak/domain/product/repository/ProductReportRepository.java
  core-domain/src/main/java/com/napzak/domain/store/code/StoreErrorCode.java
Labels: feat 🎯, 세희🐰

#134 [fix] #133 - date 메세지 중복 삽입 이슈 해결 및 일부 채팅 dto 수정
  api-server/src/main/java/com/napzak/api/domain/product/ProductChatFacade.java
  api-server/src/main/java/com/napzak/api/domain/product/controller/ProductController.java
  api-server/src/main/java/com/napzak/api/domain/product/dto/response/ProductChatInfoResponse.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/controller/ChatRestController.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/dto/response/ChatRoomListResponse.java
  chat-server/src/main/resources/static/ws-test.html
  core-domain/src/main/java/com/napzak/domain/chat/crud/chatmessage/ChatMessageSaver.java
  core-domain/src/main/java/com/napzak/domain/chat/repository/ChatMessageRepository.java
Labels: fix 🛠️, 혜린😼

#136 [feat] #137 - 채팅방 생성 실시간 알림 기능 구현
  api-server/src/main/java/com/napzak/api/domain/store/code/StoreSuccessCode.java
  api-server/src/main/java/com/napzak/api/domain/store/controller/StoreController.java
  api-server/src/main/java/com/napzak/api/domain/store/dto/response/StoreIdResponse.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/amqp/ChatDlqMessageListener.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/amqp/RabbitMQConfig.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/amqp/RoomCreatedDlqListener.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/amqp/RoomCreatedListener.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/amqp/RoomCreatedSender.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/controller/ChatRestController.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/service/ChatWebSocketService.java
  chat-server/src/main/java/com/napzak/chat/websocket/config/ChatClassMapper.java
  chat-server/src/main/java/com/napzak/chat/websocket/config/WebSocketConfig.java
  chat-server/src/main/resources/static/ws-test.html
  core-domain/src/main/java/com/napzak/domain/chat/vo/RoomCreatedPayload.java
Labels: feat 🎯, 혜린😼

#142 [feat] #143 - Dockerfile에 JVM 타임존 설정 추가
  Dockerfile-api-dev
  Dockerfile-chat-dev
  api-server/src/main/java/com/napzak/api/NapzakApiApplication.java
  chat-server/src/main/java/com/napzak/chat/NapzakChatApplication.java
Labels: feat 🎯, 혜린😼

#145 [fix] #144 - 온보딩 과정 withdraw 유저 접근 허용
  api-server/src/main/java/com/napzak/api/domain/genre/controller/GenreController.java
  api-server/src/main/java/com/napzak/api/domain/store/controller/StoreController.java
Labels: bug 🐞, fix 🛠️, 세희🐰
