Repository napzakmarket/Napzak-BE, pull requests merged in 2025-08, with the labels that each got.

#153 [fix] #152 - AWS SDK for Java v2 마이그레이션 및 메세지 isRead, isProfileNeeded 판단 로직 수정
  api-server/build.gradle
  api-server/src/main/java/com/napzak/api/domain/file/controller/FileController.java
  api-server/src/main/java/com/napzak/api/domain/file/service/FileService.java
  api-server/src/main/java/com/napzak/api/domain/file/service/S3ImageCleaner.java
  chat-server/src/main/java/com/napzak/chat/domain/chat/api/dto/response/ChatMessageListResponse.java
  common-module/build.gradle
  common-module/src/main/java/com/napzak/common/config/S3Config.java
Labels: feat 🎯, fix 🛠️, 혜린😼

#155 [fix] #154 - Micrometer system metrics disable & FileDescriptorMetrics 주입 제거
  api-server/src/main/java/com/napzak/api/NapzakApiApplication.java
  api-server/src/main/java/com/napzak/api/domain/store/service/LoginService.java
  chat-server/src/main/java/com/napzak/chat/NapzakChatApplication.java
Labels: fix 🛠️, 혜린😼

#156 [fix] #154 - actuator metrics system 호출로 인한 부트 실패 이슈 해결
  api-server/src/main/java/com/napzak/api/NapzakApiApplication.java
  chat-server/src/main/java/com/napzak/chat/NapzakChatApplication.java
Labels: fix 🛠️, 혜린😼

#149 [fix] #146 - redis Set에 add할 때 null검증 추가
  core-domain/src/main/java/com/napzak/domain/store/crud/slang/SlangRetriever.java
Labels: fix 🛠️, 세희🐰

#160 [feat] #158 - 신고 승인된 상점의 상품 isVisible = false로 변경
  api-server/src/main/java/com/napzak/api/admin/controller/AdminController.java
Labels: feat 🎯, 세희🐰

#162 [fix] #161 - 탈퇴 시 마켓 소개 초기화 및 admin api 권한 검증 추가
  api-server/src/main/java/com/napzak/api/admin/controller/AdminController.java
  api-server/src/main/java/com/napzak/api/domain/store/service/StoreService.java
  core-domain/src/main/java/com/napzak/domain/store/crud/store/StoreUpdater.java
  core-domain/src/main/java/com/napzak/domain/store/entity/StoreEntity.java
Labels: fix 🛠️, 혜린😼

#172 [fix] #167 - 채팅 관련 상품 조회, 채팅 메시지 조회 시 상품 삭제여부를 포함
  api-server/src/main/java/com/napzak/api/domain/product/ProductChatFacade.java
  api-server/src/main/java/com/napzak/api/domain/product/dto/response/ProductChatInfoResponse.java
  api-server/src/main/java/com/napzak/api/domain/product/service/ProductService.java
  core-domain/src/main/java/com/napzak/domain/chat/crud/chatmessage/ChatMessageUpdater.java
  core-domain/src/main/java/com/napzak/domain/chat/repository/ChatMessageRepository.java
  core-domain/src/main/java/com/napzak/domain/product/crud/product/ProductUpdater.java
  core-domain/src/main/java/com/napzak/domain/product/repository/ProductRepository.java
Labels: fix 🛠️, 세희🐰

#174 [feat] #173 - 신고, 탈퇴 시 채팅메시지 메타데이터 isProductDeleted 반영
  api-server/src/main/java/com/napzak/api/admin/controller/AdminController.java
  api-server/src/main/java/com/napzak/api/domain/product/ProductChatFacade.java
  api-server/src/main/java/com/napzak/api/domain/product/service/ProductService.java
  api-server/src/main/java/com/napzak/api/domain/store/StoreChatFacade.java
  api-server/src/main/java/com/napzak/api/domain/store/StoreProductFacade.java
  api-server/src/main/java/com/napzak/api/domain/store/controller/StoreController.java
  core-domain/src/main/java/com/napzak/domain/chat/crud/chatmessage/ChatMessageUpdater.java
  core-domain/src/main/java/com/napzak/domain/chat/repository/ChatMessageRepository.java
  core-domain/src/main/java/com/napzak/domain/product/crud/product/ProductRetriever.java
  core-domain/src/main/java/com/napzak/domain/product/repository/ProductRepository.java
Labels: feat 🎯, 세희🐰

#176 [deploy] #175 - docker 파일, CI CD 파일 작성 및 수정
  .github/workflows/prod-CD.yml
  .github/workflows/prod-CI.yml
  .github/workflows/prod-api-CD.yml
  .github/workflows/prod-api-CI.yml
  .github/workflows/prod-chat-CD.yml
  .github/workflows/prod-chat-CI.yml
  Dockerfile-api-prod
  Dockerfile-chat-prod
  docker-compose-api-prod.yml
  docker-compose-chat-prod.yml
Labels: deploy 🚀, 세희🐰

#181 [fix] #180 - environment 수정
  .github/workflows/prod-api-CD.yml
  .github/workflows/prod-chat-CD.yml
Labels: fix 🛠️, 세희🐰

#183 [fix] #180 - environment 수정
  .github/workflows/prod-api-CI.yml
  .github/workflows/prod-chat-CI.yml
Labels: fix 🛠️, 세희🐰

#184 [chore] main branch에 적용
  .github/workflows/prod-api-CI.yml
  .github/workflows/prod-chat-CI.yml
Labels: chore 🔍, 세희🐰
