Repository napzakmarket/Napzak-BE, pull requests merged in 2025-04, with the labels that each got.

#3 [feat] #1 - 테이블 추가 / 필드 수정, 추가
  src/main/java/com/napzak/domain/banner/core/entity/BannerEntity.java
  src/main/java/com/napzak/domain/banner/core/entity/BannerTableConstants.java
  src/main/java/com/napzak/domain/banner/core/entity/enums/BannerType.java
  src/main/java/com/napzak/domain/banner/core/vo/Banner.java
  src/main/java/com/napzak/domain/external/core/entity/LinkEntity.java
  src/main/java/com/napzak/domain/external/core/entity/LinkTableConstants.java
  src/main/java/com/napzak/domain/external/core/entity/UseTermsEntity.java
  src/main/java/com/napzak/domain/external/core/entity/UseTermsTableConstants.java
  src/main/java/com/napzak/domain/external/core/entity/enums/LinkType.java
  src/main/java/com/napzak/domain/external/core/vo/Link.java
  src/main/java/com/napzak/domain/external/core/vo/UseTerms.java
  src/main/java/com/napzak/domain/genre/core/entity/GenreEntity.java
  src/main/java/com/napzak/domain/genre/core/entity/GenreTableConstants.java
  src/main/java/com/napzak/domain/genre/core/vo/Genre.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductChatResponse.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductSaver.java
  src/main/java/com/napzak/domain/product/core/entity/ProductEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductReportEntity.java
  src/main/java/com/napzak/domain/product/core/entity/ProductReportTableConstants.java
  src/main/java/com/napzak/domain/product/core/entity/ProductTableConstants.java
  src/main/java/com/napzak/domain/product/core/entity/SearchWordEntity.java
  src/main/java/com/napzak/domain/product/core/entity/SearchWordTableConstants.java
  src/main/java/com/napzak/domain/product/core/vo/Product.java
  src/main/java/com/napzak/domain/product/core/vo/ProductReport.java
  src/main/java/com/napzak/domain/product/core/vo/ProductWithFirstPhoto.java
  src/main/java/com/napzak/domain/product/core/vo/SearchWord.java
  src/main/java/com/napzak/domain/store/core/entity/SlangEntity.java
  src/main/java/com/napzak/domain/store/core/entity/SlangTableConstants.java
  src/main/java/com/napzak/domain/store/core/entity/StorePhotoEntity.java
  src/main/java/com/napzak/domain/store/core/entity/StorePhotoTableConstants.java
  src/main/java/com/napzak/domain/store/core/entity/StoreReportEntity.java
  src/main/java/com/napzak/domain/store/core/entity/StoreReportTableConstants.java
  src/main/java/com/napzak/domain/store/core/entity/WithdrawEntity.java
  src/main/java/com/napzak/domain/store/core/entity/WithdrawTableConstants.java
  src/main/java/com/napzak/domain/store/core/entity/enums/PhotoType.java
  src/main/java/com/napzak/domain/store/core/entity/enums/Role.java
  src/main/java/com/napzak/domain/store/core/vo/Slang.java
  src/main/java/com/napzak/domain/store/core/vo/StorePhoto.java
  src/main/java/com/napzak/domain/store/core/vo/StoreReport.java
  src/main/java/com/napzak/domain/store/core/vo/Withdraw.java
Labels: feat 🎯, 세희🐰

#5 [feat] #4 - 최대 등록 가능 선호 장르 수 수정
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
Labels: feat 🎯, 세희🐰

#8 [feat] #6 - 배너리스트 조회 api 반환 json 수정
  src/main/java/com/napzak/domain/banner/api/controller/BannerController.java
  src/main/java/com/napzak/domain/banner/api/dto/response/BannerResponseList.java
  src/main/java/com/napzak/domain/banner/api/dto/response/HomeBannerResponse.java
  src/main/java/com/napzak/domain/banner/api/service/BannerService.java
  src/main/java/com/napzak/domain/banner/core/BannerRepository.java
  src/main/java/com/napzak/domain/banner/core/BannerRetriever.java
Labels: feat 🎯, 세희🐰

#10 [feat] #9 - access token 재발급 api 구현 + 로그아웃 검토
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
  src/main/java/com/napzak/domain/store/api/service/AuthenticationService.java
  src/main/java/com/napzak/global/auth/jwt/provider/JwtTokenProvider.java
  src/main/java/com/napzak/global/common/config/SecurityConfig.java
Labels: feat 🎯, 세희🐰

#11 [feat] #7 - 홈화면 인기 팔아요, 구해요 dto와 반환 데이터 수 수정
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellDto.java
Labels: feat 🎯, 세희🐰

#14 [feat] #12 - 마이페이지 정보 조회 api 수정 + 설정 서비스 외부링크 조회 api 구현
  src/main/java/com/napzak/domain/external/core/LinkRepository.java
  src/main/java/com/napzak/domain/external/core/LinkRetriever.java
  src/main/java/com/napzak/domain/external/core/entity/enums/LinkType.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/store/api/StoreLinkFacade.java
  src/main/java/com/napzak/domain/store/api/StoreProductFacade.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/response/MyPageResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/SettingLinkResponse.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
Labels: feat 🎯, 세희🐰

#15 [feat] #13 - 상점 정보 조회 시 isStoreOwner를 함께 반환하도록 수정
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreInfoResponse.java
Labels: feat 🎯, 세희🐰

#22 [feat] #19 - 상품 상세정보 조회 api 수정
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductDetailResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreStatusDto.java
  src/main/java/com/napzak/domain/store/core/StoreRepository.java
Labels: feat 🎯, 세희🐰

#23 [feat] #20 - 상품 상태 변경 api 구현
  src/main/java/com/napzak/domain/product/api/controller/ProductApi.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/request/TradeStatusRequest.java
  src/main/java/com/napzak/domain/product/api/exception/ProductErrorCode.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductUpdater.java
  src/main/java/com/napzak/domain/product/core/entity/enums/TradeStatus.java
Labels: feat 🎯, 세희🐰

#26 [feat] #25 - 장르 검색 api 수정
  src/main/java/com/napzak/domain/genre/api/GenreLinkFacade.java
  src/main/java/com/napzak/domain/genre/api/controller/GenreController.java
  src/main/java/com/napzak/domain/genre/api/exception/GenreSuccessCode.java
  src/main/java/com/napzak/global/common/exception/dto/SuccessResponse.java
Labels: feat 🎯, 혜린😼

#28 [feat] #24 - 추천 검색어, 추천 장르 조회 api 구현
  src/main/java/com/napzak/domain/genre/core/GenreRepository.java
  src/main/java/com/napzak/domain/genre/core/GenreRetriever.java
  src/main/java/com/napzak/domain/product/api/ProductGenreFacade.java
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/RecommendGenreDto.java
  src/main/java/com/napzak/domain/product/api/dto/response/RecommendResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/RecommendSearchWordDto.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/SearchWordRepository.java
  src/main/java/com/napzak/domain/product/core/SearchWordRetriever.java
  src/main/java/com/napzak/domain/store/api/StoreGenreFacade.java
Labels: feat 🎯, 세희🐰

#32 [feat] #31 - 상품 리스트 조회 관련 수정
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyListResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellListResponse.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
Labels: feat 🎯, 혜린😼

#38 [feat] #37 - 신고/탈퇴 관련 api 구현
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/request/ProductReportRequest.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductReportResponse.java
  src/main/java/com/napzak/domain/product/api/exception/ProductSuccessCode.java
  src/main/java/com/napzak/domain/product/api/service/ProductService.java
  src/main/java/com/napzak/domain/product/core/ProductReportRepository.java
  src/main/java/com/napzak/domain/product/core/ProductReportSaver.java
  src/main/java/com/napzak/domain/product/core/entity/ProductReportEntity.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/request/StoreReportRequest.java
  src/main/java/com/napzak/domain/store/api/dto/request/StoreWithdrawRequest.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreReportResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/StoreWithdrawResponse.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/StoreReportRepository.java
  src/main/java/com/napzak/domain/store/core/StoreReportSaver.java
  src/main/java/com/napzak/domain/store/core/StoreRetriever.java
  src/main/java/com/napzak/domain/store/core/StoreUpdater.java
  src/main/java/com/napzak/domain/store/core/WithdrawRepository.java
  src/main/java/com/napzak/domain/store/core/WithdrawSaver.java
  src/main/java/com/napzak/domain/store/core/entity/WithdrawEntity.java
  src/main/java/com/napzak/domain/store/core/entity/WithdrawTableConstants.java
  src/main/java/com/napzak/global/common/config/WebConfig.java
  src/main/java/com/napzak/global/common/util/discord/DiscordWebhookProperties.java
  src/main/java/com/napzak/global/common/util/discord/DiscordWebhookSender.java
Labels: feat 🎯, 혜린😼

#39 [feat] #37 - 홈화면 추천상품 조회 api 리팩토링
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductRecommendListResponse.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustom.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
Labels: challenge 🏆, refactor 🔁, 혜린😼

#41 [deploy] #40 - github workflow 수정
  .github/workflows/dev-CD.yml
  .github/workflows/prod-CD.yml
Labels: deploy 🚀, 혜린😼

#43 [deploy] #42 - docker-compose 수정
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: deploy 🚀, 혜린😼

#45 [feat] #44 - [feat] 회원가입 시 기본이미지 삽입 구현
  src/main/java/com/napzak/domain/product/api/controller/ProductApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/StorePhotoRepository.java
  src/main/java/com/napzak/domain/store/core/StorePhotoRetriever.java
  src/main/java/com/napzak/domain/store/core/StoreUpdater.java
  src/main/java/com/napzak/domain/store/core/entity/StorePhotoEntity.java
Labels: feat 🎯, 혜린😼

#49 [fix] #48 - 상품 삭제 api 관련 사진도 함께 삭제
  src/main/java/com/napzak/domain/product/core/ProductPhotoRemover.java
  src/main/java/com/napzak/domain/product/core/ProductPhotoRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRemover.java
Labels: fix 🛠️, 세희🐰

#52 [feat] #51 - 로그인 response에 refresh token 포함하여 반환
  src/main/java/com/napzak/domain/store/api/controller/StoreApi.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
Labels: feat 🎯, 세희🐰

#53 [feat] #50 - 애플 소셜로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/napzak/domain/store/api/exception/StoreErrorCode.java
  src/main/java/com/napzak/domain/store/api/service/LoginService.java
  src/main/java/com/napzak/global/auth/client/apple/dto/ApplePublicKeyDto.java
  src/main/java/com/napzak/global/auth/client/apple/dto/ApplePublicKeyResponse.java
  src/main/java/com/napzak/global/auth/client/apple/dto/AppleTokenResponseDto.java
  src/main/java/com/napzak/global/auth/client/exception/OAuthErrorCode.java
  src/main/java/com/napzak/global/auth/client/service/AppleSocialService.java
  src/main/java/com/napzak/global/auth/client/service/PublicKeyFinder.java
Labels: feat 🎯, 세희🐰

#57 [fix] #56 - jwt Auth filter에 ONBOARDING 관련 포함
  src/main/java/com/napzak/global/auth/jwt/filter/JwtAuthenticationFilter.java
Labels: fix 🛠️, 세희🐰
