Repository napzakmarket/Napzak-BE, pull requests merged in 2025-05, with the labels that each got.

#59 [feat] #58 - 상품 수정을 위한 정보 조회 api의 response에 genreId 추가
  src/main/java/com/napzak/domain/product/api/controller/ProductController.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductBuyModifyResponse.java
  src/main/java/com/napzak/domain/product/api/dto/response/ProductSellModifyResponse.java
Labels: feat 🎯, 세희🐰

#61 [feat] #60 - access token을 직접 입력받아 로그인하는 api 추가
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/service/LoginService.java
  src/main/java/com/napzak/global/auth/client/service/KakaoSocialService.java
Labels: feat 🎯, 세희🐰

#68 [feat] #67 - role 변경 api 구현
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/request/RoleDto.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
Labels: feat 🎯, 세희🐰

#66 [Feat] #65 - 추가/변경 엔티티 작업, 약관 정보 조회 api 수정, 동의약관 저장 api 구현
  src/main/java/com/napzak/domain/external/core/TermsBundleRepository.java
  src/main/java/com/napzak/domain/external/core/TermsBundleRetriever.java
  src/main/java/com/napzak/domain/external/core/UseTermsRepository.java
  src/main/java/com/napzak/domain/external/core/UseTermsRetriever.java
  src/main/java/com/napzak/domain/external/core/entity/ConfigConstants.java
  src/main/java/com/napzak/domain/external/core/entity/ConfigEntity.java
  src/main/java/com/napzak/domain/external/core/entity/TermsBundleConstants.java
  src/main/java/com/napzak/domain/external/core/entity/TermsBundleEntity.java
  src/main/java/com/napzak/domain/external/core/entity/UseTermsEntity.java
  src/main/java/com/napzak/domain/external/core/entity/UseTermsTableConstants.java
  src/main/java/com/napzak/domain/external/core/entity/enums/LinkType.java
  src/main/java/com/napzak/domain/external/core/entity/enums/TermsType.java
  src/main/java/com/napzak/domain/external/core/vo/Config.java
  src/main/java/com/napzak/domain/external/core/vo/TermsBundle.java
  src/main/java/com/napzak/domain/external/core/vo/UseTerms.java
  src/main/java/com/napzak/domain/store/api/StoreTermsBundleFacade.java
  src/main/java/com/napzak/domain/store/api/StoreUseTermsFacade.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/dto/response/OnboardingTermsListResponse.java
  src/main/java/com/napzak/domain/store/api/dto/response/TermsDto.java
  src/main/java/com/napzak/domain/store/api/exception/StoreSuccessCode.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
  src/main/java/com/napzak/domain/store/core/TermsAgreementRepository.java
  src/main/java/com/napzak/domain/store/core/TermsAgreementSaver.java
  src/main/java/com/napzak/domain/store/core/entity/TermsAgreementConstants.java
  src/main/java/com/napzak/domain/store/core/entity/TermsAgreementEntity.java
  src/main/java/com/napzak/domain/store/core/vo/TermsAgreement.java
Labels: feat 🎯, 세희🐰

#70 [fix] #69 - 닉네임 검증 오류 해결
  src/main/java/com/napzak/domain/store/core/entity/SlangRetriever.java
  src/main/java/com/napzak/global/common/slang/SlangFilter.java
Labels: fix 🛠️, 혜린😼

#72 [refactor] #71 - photoSequence -> sequence 필드명 변경
  src/main/java/com/napzak/domain/product/api/dto/response/ProductPhotoDto.java
Labels: refactor 🔁, 세희🐰

#78 [feat] #77 - jwtauthfilter createAuthentication에 withdrawn 유저에 대해서도 인…
  src/main/java/com/napzak/global/auth/jwt/filter/JwtAuthenticationFilter.java
Labels: feat 🎯, 세희🐰

#81 [feat] #80 - 탈퇴 api db변경 플로우 추가
  src/main/java/com/napzak/domain/interest/core/InterestRemover.java
  src/main/java/com/napzak/domain/interest/core/InterestRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRepository.java
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
  src/main/java/com/napzak/domain/product/core/ProductRetriever.java
  src/main/java/com/napzak/domain/product/core/ProductUpdater.java
  src/main/java/com/napzak/domain/store/api/StoreInterestFacade.java
  src/main/java/com/napzak/domain/store/api/StoreProductFacade.java
  src/main/java/com/napzak/domain/store/api/controller/StoreController.java
  src/main/java/com/napzak/domain/store/api/service/StoreService.java
Labels: feat 🎯, 세희🐰

#85 [#84] Feat(ProductRepositoryCustomImpl): 홈화면 인기상품 판매중만 노출되도록 필터링 조건 추가
  src/main/java/com/napzak/domain/product/core/ProductRepositoryCustomImpl.java
Labels: feat 🎯, 혜린😼
