Repository napzakmarket/Napzak-BE, pull requests merged in 2025-09, with the labels that each got.

#200 [deploy] #194 - chat 서버 무중단배포 환경 구축
  .github/workflows/prod-chat-CD.yml
  docker-compose-chat-blue-prod.yml
  docker-compose-chat-deps-prod.yml
  docker-compose-chat-green-prod.yml
Labels: deploy 🚀, 세희🐰

#202 [deploy] #194 - 환경변수 오타 수정
  .github/workflows/prod-chat-CD.yml
Labels: fix 🛠️, 세희🐰

#207 [fix] #203 - LocalDateTime 설정으로 500 리턴 제한
  core-domain/src/main/java/com/napzak/domain/chat/crud/chatmessage/ChatMessageRetriever.java
  core-domain/src/main/java/com/napzak/domain/chat/vo/ChatMessage.java
Labels: fix 🛠️, 세희🐰

#210 [deploy] - 차단 기능 구현 prod 배포
  api-server/src/main/java/com/napzak/api/domain/product/ProductStoreFacade.java
  api-server/src/main/java/com/napzak/api/domain/product/controller/ProductController.java
  api-server/src/main/java/com/napzak/api/domain/product/dto/response/ProductChatInfoResponse.java
  api-server/src/main/java/com/napzak/api/domain/store/code/StoreSuccessCode.java
  api-server/src/main/java/com/napzak/api/domain/store/controller/StoreController.java
  api-server/src/main/java/com/napzak/api/domain/store/dto/response/StoreInfoResponse.java
  api-server/src/main/java/com/napzak/api/domain/store/service/StoreService.java
  core-domain/src/main/java/com/napzak/domain/store/code/StoreErrorCode.java
  core-domain/src/main/java/com/napzak/domain/store/crud/storeblock/StoreBlockRemover.java
  core-domain/src/main/java/com/napzak/domain/store/crud/storeblock/StoreBlockRetriever.java
  core-domain/src/main/java/com/napzak/domain/store/crud/storeblock/StoreBlockSaver.java
  core-domain/src/main/java/com/napzak/domain/store/entity/StoreBlockEntity.java
  core-domain/src/main/java/com/napzak/domain/store/entity/StoreBlockTableConstants.java
  core-domain/src/main/java/com/napzak/domain/store/repository/StoreBlockRepository.java
  core-domain/src/main/java/com/napzak/domain/store/vo/BlockStatus.java
Labels: deploy 🚀, 혜린😼

#212 [#211] docker-compose-dev에 pull_policy 추가
  docker-compose-dev.yml
Labels: deploy 🚀, 혜린😼

#213 [deploy] prod 배포
  docker-compose-dev.yml
Labels: deploy 🚀, 혜린😼

#215 [feat] #214 - 채팅 관련 정보 조회 응답 필드 수정 및 금지 닉네임 지정
  api-server/src/main/java/com/napzak/api/domain/store/service/StoreService.java
  core-domain/src/main/java/com/napzak/domain/store/crud/storeblock/StoreBlockRetriever.java
  core-domain/src/main/java/com/napzak/domain/store/vo/BlockStatus.java
Labels: feat 🎯, 혜린😼

#216 [deploy] 닉네임 금칙어 설정, 채팅차단여부 의미 수정 prod 배포
  api-server/src/main/java/com/napzak/api/domain/store/service/StoreService.java
  core-domain/src/main/java/com/napzak/domain/store/crud/storeblock/StoreBlockRetriever.java
  core-domain/src/main/java/com/napzak/domain/store/vo/BlockStatus.java
Labels: deploy 🚀, 혜린😼
